config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.list = List.find(params[:list_id])
    @bookmark.save
    redirect_to list_path(params[:list_id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end

end


# @bookmark = Bookmark.new({comment: params[:bookmark][:comment], movie: Movie.find(params[:bookmark][:movie_id]), list: List.find(params[:list_id])})

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    set_list
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Movie lists</h1>
<ul>
<% @lists.each do |list| %>
  <li><%= link_to list.name, list_path(list) %></li>
<% end %>
</ul>
<p><%= link_to "+ Add a new list", new_list_path  %></p>

app/views/lists/new.html.erb
<div class="container">
<h1>Create a new list</h1>
  <div class="row">
    <div class="col-xs-12 col-sm-12">
    <%= simple_form_for [@list] do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
  <p> <%= link_to "Back to list", lists_path %></p>
</div>

app/views/lists/show.html.erb
<div class="my-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key%>'); padding:150px; background-cover: fill;">
  <h1 class="page-title"><%= @list.name%></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
        <% @list.movies.each do |movie| %>
          <div class="movie-card">
            <div class="my-image-column">
              <img class="movie-poster" src="<%= movie.poster_url %>" alt="<%= movie.title %>">
            </div>
            <div class="my-description-column">
              <% bookmark = movie.bookmarks.where(list_id: @list.id).first %>
              <strong class="title-bold"><%= movie.title %></strong> | <em class="synopsis-italic"><%= movie.overview %></em><br/><br/>
              <%= bookmark.comment %> <br/> Added: <%= movie.created_at.strftime("%d/%m/%Y") %>
              <%= link_to "🗑", list_bookmark_path(@list.id, bookmark.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
            </div>
          </div>
        <% end %>
      <a href="#add-form"><button class="btn btn-primary" id="add-button"><%= "+ Add a movie" %></button></a>
      <br/><br/>
      <p><%= link_to "Back to movie lists", lists_path%></p>
      <br/>
    </div>
  </div>
  <div id="add-form" class="display-none">
      <h3>Add a movie to <%= @list.name %></h3>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.input :movie_id, collection: Movie.all %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

<!-- CHECK THE PROBLEM OF ADD BUTTON -->



<script>
  const addForm = document.getElementById("add-form");
  const addButton = document.getElementById("add-button");
  console.log(addForm);

  addButton.addEventListener("click", (event) => {
    addForm.classList.remove("display-none");
  })
</script>